[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor="#00A8CC"
backgroundColor="#E8FCF7"
secondaryBackgroundColor="#D6F7EE"
textColor="#1A1A1A"
font="sans serif"
