[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#B7A4FF"
backgroundColor = "#1A1625"
secondaryBackgroundColor = "#251f35"
textColor = "#EDEAFF"
font = "sans serif"
